### ISSUE TITLE
Gaussian kernels

### ISSUE THREAD

**Issue by GoWebProd** [rust-ndarray/ndarray-stats#60]
Hello. Do you have in plans port of https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html#scipy.stats.gaussian_kde ?

**Comment by LukeMathWalker** [comment]
It's not currently on our radar - what is your use case?

**Comment by GoWebProd** [comment]
I'm writing library for financial portfolio optimizing and I need CVaR function like this:

https://github.com/robertmartin8/PyPortfolioOpt/blob/c73d028ddf050a5e1e2a58e393d3696e42c2df12/pypfopt/objective_functions.py#L110

**Comment by LukeMathWalker** [comment]
Understood - it's not something I plan to work on in the near future, but if you are willing to contribute it I'd be happy to review the implementation.

**Comment by GoWebProd** [comment]
Understood, thanks. I will try to implement.
