### ISSUE TITLE
Covariance not working in 0.4

### ISSUE THREAD

**Issue by ronniec95** [rust-ndarray/ndarray-stats#73]
This fails in 0.4

 ```
   use ndarray_stats::CorrelationExt;
    let or = ArrayView2::from_shape([prices.ncols(), prices.nrows() - 1], &pct_returns).unwrap();
    let cov_matrix = or.cov(1.0).expect("Could not calculate covariance matrix");
```

with

```
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use ndarray_stats::correlation::CorrelationExt;
```

but has no such issues in 0.3

A regression?

**Comment by jturner314** [comment]
Are you sure that the versions of `ndarray-stats` and `ndarray` that you're using match? `ndarray-stats` 0.4 provides functionality for `ndarray` 0.14, while `ndarray-stats` 0.3 provides functionality for `ndarray` 0.13.

**Comment by ronniec95** [comment]
I see, but then the ndarray-linalg crate stops working. I'll wait till all three are in sync.
