### ISSUE TITLE
Support master branch of `ndarray`

### ISSUE THREAD

**Issue by duskmoon314** [rust-ndarray/ndarray-stats#97]
I want to use both methods in `ndarray`'s master branch and this crate. But this crate only supports specific `ndarray` (0.15.0 for now), which is incompatible with the master branch of `ndarray`.

I wonder if there is a way to use `ndarray-stats` and `ndarray`'s master branch instead of cloning and changing the dependencies to git URLs.

Maybe merging `ndarray-stats` to `ndarray` and forming a workspace is a solution. In such a way, [multiple locations](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations) could be used.

**Comment by altunenes** [comment]
that would be very nice.

**Comment by bluss** [comment]
I would not recommend using the crates through git. It's best to use released versions. Volunteer to manage releases to make releases where those are needed.
